### PR TITLE
Add multishot powerup

### PR DESCRIPTION
**Pull request by LordDeatHunter**
The magic "spread angle" numbers could probably use some tweaking.
Here's how it currently looks ingame (triple shot, screenshot taken mid gameplay):
image

Also, not completely satisfied with how the "distance" forms, maybe we can have some randomization or smoothing out in the future. (this is a lot of projectiles, mostly as an example of how they stack over time)
image

I also made it a guaranteed drop from the Repeater boss. Had to make a new loot-table for it.
By default, it's a 1% drop from other enemies.

### CODE REVIEW

**Comment by varoonp123** [comment]
CI is failing for an unenlightening reason. We will need to merge #111 first.

**Comment by cdsupina** [comment]
@varoonp123 and I tested this and found that when the Juggernaut character has multi-shot, the projectiles collide with each other due to their hitbox. Perhaps adjust the position or angle of the projectiles.

**Comment by cdsupina** [comment]
Pull main to fix CI.

**Comment by LordDeatHunter** [comment]
(copied from discord)

Update on this: I can't find a clean all-encompassing solution.
1. Spreading the bullets a bit initially kinda works, but it gets janky with more projectiles:
- if the "spread" amount isn't increased over time, the bullets start colliding
- otherwise, they keep spreading out, making "horizontal lines" across the map after a couple of powerups
2. A similar solution would be to instead disable the collider on the bullets when they're spawned, and enable it some 0.5s after. Not sure how this will affect gameplay. It might be the most "middle ground" solution.
3. Disabling "explosions" (despawning) on bullet collision makes it weird (they ricochet a lot & makes their movement very unpredictable)
4. Disabling collision between same-type bullets - should in theory work, but I'm not sure on the affect on gameplay.
5. The projectile powerups only affecting the main character. Bullet-characters either not being able to pick up the powerup, not getting anything, or getting a different power.

I'll leave the PR open for now, in case there are some other ideas 🙂

**Comment by LordDeatHunter** [comment]
Updated look of the projectile arc:
image

**Comment by LordDeatHunter** [comment]
Juggernaut is now also sexy 💗
However, it's hard to fight the Repeater boss, since all the projectiles launch the boss upwards. Also noticeable with just 2 projectiles.

image

**Comment by cdsupina** [comment]
We can try decreasing the mass of the projectiles, or increasing the speed (so it can recover faster) or mass of the boss. Either way though, I think for now it's fine and this is just a matter of balancing some values.

**Review by varoonp123 — APPROVED** [review]
A good step towards bullet hell. We are false advertising rn... ill merge when ci passes

**Pull request merged**
